const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""

global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"


global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SULTANBKR/SULTAN-KHAN";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VaXTvQ7JuyAHXjJBs61T";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029VaXTvQ7JuyAHXjJBs61T" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/IMG_20240101_133420.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923115971525" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923194778990";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923115971525,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://yousaf khan-vtsf.onrender.com/";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_11_24_05_24_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTQ0LFxuICAgICAgICA4OCxcbiAgICAgICAgMzUsXG4gICAgICAgIDQ0LFxuICAgICAgICAyMjAsXG4gICAgICAgIDQ5LFxuICAgICAgICA2NixcbiAgICAgICAgODcsXG4gICAgICAgIDQ4LFxuICAgICAgICAyMzYsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTg5LFxuICAgICAgICAxMTcsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTIyLFxuICAgICAgICAxMzMsXG4gICAgICAgIDExMyxcbiAgICAgICAgMTc3LFxuICAgICAgICAxODYsXG4gICAgICAgIDMxLFxuICAgICAgICA2NixcbiAgICAgICAgMjQwLFxuICAgICAgICA3NixcbiAgICAgICAgNzMsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMjM1LFxuICAgICAgICAxNzEsXG4gICAgICAgIDEzLFxuICAgICAgICA0LFxuICAgICAgICAxMjksXG4gICAgICAgIDE2MyxcbiAgICAgICAgMTI1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2OSxcbiAgICAgICAgMzAsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMjAyLFxuICAgICAgICA4NyxcbiAgICAgICAgMjUsXG4gICAgICAgIDYxLFxuICAgICAgICAxNTIsXG4gICAgICAgIDE0OCxcbiAgICAgICAgNCxcbiAgICAgICAgMjQyLFxuICAgICAgICAxMzUsXG4gICAgICAgIDEzMyxcbiAgICAgICAgNjcsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTY2LFxuICAgICAgICA3MSxcbiAgICAgICAgMTEwLFxuICAgICAgICAyMyxcbiAgICAgICAgMTczLFxuICAgICAgICA5NCxcbiAgICAgICAgNTQsXG4gICAgICAgIDE4MyxcbiAgICAgICAgNDksXG4gICAgICAgIDQwLFxuICAgICAgICAxNzksXG4gICAgICAgIDI0LFxuICAgICAgICAxNzgsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjUzLFxuICAgICAgICAyMTEsXG4gICAgICAgIDExN1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTkyLFxuICAgICAgICA1MyxcbiAgICAgICAgMjUwLFxuICAgICAgICAyMDIsXG4gICAgICAgIDE2LFxuICAgICAgICA4OSxcbiAgICAgICAgOTUsXG4gICAgICAgIDE5NixcbiAgICAgICAgMTAsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTIyLFxuICAgICAgICA4NixcbiAgICAgICAgNDQsXG4gICAgICAgIDksXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTE5LFxuICAgICAgICAxMTgsXG4gICAgICAgIDE0LFxuICAgICAgICAxMDksXG4gICAgICAgIDEzNixcbiAgICAgICAgMTQxLFxuICAgICAgICAxNzIsXG4gICAgICAgIDgzLFxuICAgICAgICAxNTgsXG4gICAgICAgIDcsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMTA2LFxuICAgICAgICA3LFxuICAgICAgICAxODQsXG4gICAgICAgIDYzLFxuICAgICAgICAyMzksXG4gICAgICAgIDczXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0NyxcbiAgICAgICAgMzksXG4gICAgICAgIDE1OSxcbiAgICAgICAgNSxcbiAgICAgICAgMzYsXG4gICAgICAgIDg0LFxuICAgICAgICAxNTgsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMjMxLFxuICAgICAgICAxLFxuICAgICAgICAzNixcbiAgICAgICAgMjAsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMzYsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTc1LFxuICAgICAgICAxNDYsXG4gICAgICAgIDE2OSxcbiAgICAgICAgNyxcbiAgICAgICAgMjMxLFxuICAgICAgICA5OSxcbiAgICAgICAgMjIzLFxuICAgICAgICAyMTgsXG4gICAgICAgIDUzLFxuICAgICAgICA0NSxcbiAgICAgICAgODYsXG4gICAgICAgIDMzLFxuICAgICAgICAyNDEsXG4gICAgICAgIDIzMyxcbiAgICAgICAgNDcsXG4gICAgICAgIDEyNixcbiAgICAgICAgNzRcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDAsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMjE5LFxuICAgICAgICAxMzQsXG4gICAgICAgIDU4LFxuICAgICAgICAzNCxcbiAgICAgICAgNTMsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMjMsXG4gICAgICAgIDQ4LFxuICAgICAgICAzMSxcbiAgICAgICAgMTkxLFxuICAgICAgICA3MSxcbiAgICAgICAgNjAsXG4gICAgICAgIDk3LFxuICAgICAgICAyMTYsXG4gICAgICAgIDE3MixcbiAgICAgICAgNzksXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTM2LFxuICAgICAgICA0MSxcbiAgICAgICAgMTMsXG4gICAgICAgIDg5LFxuICAgICAgICAxODcsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTgsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTEyLFxuICAgICAgICAxMjAsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMjMyLFxuICAgICAgICA3N1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMTMsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMTUzLFxuICAgICAgICAyMDQsXG4gICAgICAgIDg0LFxuICAgICAgICA5NCxcbiAgICAgICAgMjQwLFxuICAgICAgICA2NixcbiAgICAgICAgMjcsXG4gICAgICAgIDkyLFxuICAgICAgICA0MSxcbiAgICAgICAgMjAsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTM1LFxuICAgICAgICAyMTIsXG4gICAgICAgIDUyLFxuICAgICAgICAyNTIsXG4gICAgICAgIDU3LFxuICAgICAgICAxNzEsXG4gICAgICAgIDEzOCxcbiAgICAgICAgNixcbiAgICAgICAgMTAsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTU0LFxuICAgICAgICAxMzksXG4gICAgICAgIDExMSxcbiAgICAgICAgMTg1LFxuICAgICAgICAyMjYsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTg1LFxuICAgICAgICAxNjEsXG4gICAgICAgIDMwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDEyMCxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICAxMzgsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgMTcyLFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAyNTAsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDQsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDEwLFxuICAgICAgICAgIDkxLFxuICAgICAgICAgIDE1MCxcbiAgICAgICAgICAxNTAsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDksXG4gICAgICAgICAgMTAsXG4gICAgICAgICAgMjYsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDI2LFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICA1OSxcbiAgICAgICAgICAxNjQsXG4gICAgICAgICAgMTAyXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDExOCxcbiAgICAgICAgICAxMDcsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDE3MixcbiAgICAgICAgICAxMSxcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMzUsXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDE3NyxcbiAgICAgICAgICAyMyxcbiAgICAgICAgICA1MixcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAyNDYsXG4gICAgICAgICAgODksXG4gICAgICAgICAgMjM2LFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgMjIxLFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICA4MSxcbiAgICAgICAgICA1NCxcbiAgICAgICAgICAxNTEsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMTA1LFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDNcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNjksXG4gICAgICAgIDEyLFxuICAgICAgICA0MyxcbiAgICAgICAgMjM1LFxuICAgICAgICA2NyxcbiAgICAgICAgMjAsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMjE2LFxuICAgICAgICAxOTIsXG4gICAgICAgIDIwOCxcbiAgICAgICAgNjEsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTA2LFxuICAgICAgICAxOTcsXG4gICAgICAgIDE1LFxuICAgICAgICA5NCxcbiAgICAgICAgMTM0LFxuICAgICAgICAxNTksXG4gICAgICAgIDIwMyxcbiAgICAgICAgNDYsXG4gICAgICAgIDEsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTAwLFxuICAgICAgICAxMzMsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTQyLFxuICAgICAgICAxNjIsXG4gICAgICAgIDQ1LFxuICAgICAgICA2NCxcbiAgICAgICAgNDgsXG4gICAgICAgIDQ3LFxuICAgICAgICAxOTgsXG4gICAgICAgIDE4LFxuICAgICAgICA0OCxcbiAgICAgICAgMTg4LFxuICAgICAgICAxNTIsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMTU0LFxuICAgICAgICA5MSxcbiAgICAgICAgMTY1LFxuICAgICAgICAyMDMsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMzksXG4gICAgICAgIDE3MyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxNTMsXG4gICAgICAgIDI1LFxuICAgICAgICAyOSxcbiAgICAgICAgMzAsXG4gICAgICAgIDE4LFxuICAgICAgICA2OSxcbiAgICAgICAgNjEsXG4gICAgICAgIDcxLFxuICAgICAgICA4MCxcbiAgICAgICAgNDAsXG4gICAgICAgIDgwLFxuICAgICAgICAxODMsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTI5LFxuICAgICAgICA4NixcbiAgICAgICAgODAsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMCxcbiAgICAgICAgMTI4XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxNzYsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiQnZVcm5zdFF0MG5hQkMyWXBjU2hIaGh6a0Raazk1ZWN6ZU1JRlJIYTlOUT1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMxOTQ3Nzg5OTBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkRFNTY1N0U4ODVFNTZBQzIwRjVGMTUzQjhDRjRFRkREXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNjU0OTg3N1xuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzE5NDc3ODk5MEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiOUFCNTA4N0IwRDc3MjA0OUZCMDQxMDYzMjAzNjJBRDFcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzE2NTQ5ODc4XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIjZtazJXMnh4UWdlY2Jid0RIQjZPeVFcIixcbiAgXCJwaG9uZUlkXCI6IFwiOWE1NWUwYWYtNTY5MC00ZDAxLWE0YTQtMDI5Yzk1YTBmMWExXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDIwNCxcbiAgICAgIDE2NixcbiAgICAgIDIwNyxcbiAgICAgIDE4MCxcbiAgICAgIDEyMCxcbiAgICAgIDEzMixcbiAgICAgIDExNSxcbiAgICAgIDI0NCxcbiAgICAgIDE2OSxcbiAgICAgIDk5LFxuICAgICAgMTk4LFxuICAgICAgMjM4LFxuICAgICAgMTAxLFxuICAgICAgMTM5LFxuICAgICAgODksXG4gICAgICAyMDMsXG4gICAgICAzNSxcbiAgICAgIDQ1LFxuICAgICAgMjI0LFxuICAgICAgMTQ0XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDU1LFxuICAgICAgMTk2LFxuICAgICAgODcsXG4gICAgICA4MyxcbiAgICAgIDEwOCxcbiAgICAgIDE0OCxcbiAgICAgIDE4OSxcbiAgICAgIDExNSxcbiAgICAgIDc2LFxuICAgICAgNjIsXG4gICAgICAxNjIsXG4gICAgICAxODMsXG4gICAgICA1LFxuICAgICAgNTMsXG4gICAgICA1OSxcbiAgICAgIDQ3LFxuICAgICAgOTQsXG4gICAgICAxMDYsXG4gICAgICAxNzYsXG4gICAgICA3NlxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJLMjI1QUg5WVwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTIzMTk0Nzc4OTkwOjEyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwiQmFsb2NoXCIsXG4gICAgXCJsaWRcIjogXCIxMTA1ODI5NzU5NzE0MDc6MTJAbGlkXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDUHlSMS9JRkVPN3h3YklHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJRUlBuYlVkOWd3eVV1dy9venJzZjkya28xMXJRR0hZUHZlM2xTK2pKeUhrPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIjNNVk9zQ1g5TUtHS29lRXFNQlNZYTh1cHdIVG9EamtMcTA2dktwQ0hLYk5Cayt2V0xTU0htOGFzelVvdy9FQWNtMGQ2cGxUb0U4dGhrOHFqRkpWZkJBPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcImc2WnlmY0lUTjdDUDNCcG1mZ1RaeWNRb2hKekZoVzFtVU5Ybnl5OW1YQksxaXdKSk5GUjhIM0EvcE9KTGJWVzlmbHE0YjMrMVJnaWVyMmJnSDVPdmdBPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjkyMzE5NDc3ODk5MDoxMkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDIzMSxcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICAxMixcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICAyMDYsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDMxLFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAxMDUsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDkwLFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAyNCxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMTIxXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MTY1NDk4NzQsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFJd1ZcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUl3Vi5qc29uIjogIntcImtleURhdGFcIjpcIlJkWURxZGU2YkcweXZrV2NYbk1Fck1ZeFBFenJwWE41NGtLYmNwbUJRWGs9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTU4MjY4MDMxNixcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzE2NTQ5ODc3OTQyXCJ9Igp9" ;


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: SULTAN KHAN Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.9",
  caption : process.env.CAPTION || "سلطان➳🇲R" , // ```『 SULTAN KHAN BALOCH  』```", //*『SULTAN • KHAN BALOCH』*\n https://youtube.com/@Y.BGamer110"),
 
  author : process.env.PACK_AUTHER|| "SULTAN BALOCH",
  packname: process.env.PACK_NAME || "❤️",
  botname : process.env.BOT_NAME  || "SULTAN KHAN",
  ownername:process.env.OWNER_NAME|| "SULTAN KHAN",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "public",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SULTAN KHAN",



};

























global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
