const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""

global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"


global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SULTANBKR/SULTAN-KHAN";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VaXTvQ7JuyAHXjJBs61T";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029VaXTvQ7JuyAHXjJBs61T" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/IMG_20240101_133420.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923115971525" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923194778990";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923115971525,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://yousaf khan-vtsf.onrender.com/";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_09_47_05_24_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjMyLFxuICAgICAgICAxNTAsXG4gICAgICAgIDcyLFxuICAgICAgICAxNjgsXG4gICAgICAgIDEyLFxuICAgICAgICAxNTQsXG4gICAgICAgIDUwLFxuICAgICAgICAxNDcsXG4gICAgICAgIDUwLFxuICAgICAgICAzMCxcbiAgICAgICAgMzcsXG4gICAgICAgIDIwNixcbiAgICAgICAgOTgsXG4gICAgICAgIDIxNixcbiAgICAgICAgMTk2LFxuICAgICAgICAyMTEsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMTk4LFxuICAgICAgICA4NSxcbiAgICAgICAgOTMsXG4gICAgICAgIDEzNixcbiAgICAgICAgNDUsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMjcsXG4gICAgICAgIDg5LFxuICAgICAgICAzMixcbiAgICAgICAgMTkxLFxuICAgICAgICAxMTQsXG4gICAgICAgIDE0MyxcbiAgICAgICAgNTMsXG4gICAgICAgIDE3LFxuICAgICAgICA5NVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMTQsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTYyLFxuICAgICAgICAxMDIsXG4gICAgICAgIDE5MixcbiAgICAgICAgMTYyLFxuICAgICAgICAxMjUsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTgyLFxuICAgICAgICA2OCxcbiAgICAgICAgNDksXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTkxLFxuICAgICAgICA5OSxcbiAgICAgICAgMTQ2LFxuICAgICAgICAxNDcsXG4gICAgICAgIDQwLFxuICAgICAgICAxOTAsXG4gICAgICAgIDE4MCxcbiAgICAgICAgMTIxLFxuICAgICAgICAxNjQsXG4gICAgICAgIDkyLFxuICAgICAgICA4NixcbiAgICAgICAgMjUyLFxuICAgICAgICAyMyxcbiAgICAgICAgMTY3LFxuICAgICAgICAxMDgsXG4gICAgICAgIDEzNCxcbiAgICAgICAgODEsXG4gICAgICAgIDE0NixcbiAgICAgICAgMjIxLFxuICAgICAgICA3OFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTc2LFxuICAgICAgICAxMjEsXG4gICAgICAgIDEzNixcbiAgICAgICAgMjM5LFxuICAgICAgICAxNixcbiAgICAgICAgMjI1LFxuICAgICAgICA0OCxcbiAgICAgICAgMTAyLFxuICAgICAgICA3OSxcbiAgICAgICAgNzIsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTc5LFxuICAgICAgICAxMDksXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTE4LFxuICAgICAgICAxNzUsXG4gICAgICAgIDYxLFxuICAgICAgICA3MixcbiAgICAgICAgMjQ5LFxuICAgICAgICAxODIsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjIsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTc2LFxuICAgICAgICA2NSxcbiAgICAgICAgMjMyLFxuICAgICAgICA1MyxcbiAgICAgICAgMTQzLFxuICAgICAgICA1OCxcbiAgICAgICAgMjE1LFxuICAgICAgICAxMDYsXG4gICAgICAgIDEyNFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjMsXG4gICAgICAgIDI0LFxuICAgICAgICAxODMsXG4gICAgICAgIDczLFxuICAgICAgICA5MyxcbiAgICAgICAgNDAsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMTk4LFxuICAgICAgICAzMSxcbiAgICAgICAgNyxcbiAgICAgICAgMTMwLFxuICAgICAgICAyMTksXG4gICAgICAgIDE2MyxcbiAgICAgICAgMTIzLFxuICAgICAgICA0NCxcbiAgICAgICAgMTkyLFxuICAgICAgICAxMzQsXG4gICAgICAgIDEyMCxcbiAgICAgICAgNzYsXG4gICAgICAgIDUsXG4gICAgICAgIDY5LFxuICAgICAgICAxMDUsXG4gICAgICAgIDE2MixcbiAgICAgICAgMjE3LFxuICAgICAgICAxMTMsXG4gICAgICAgIDExMixcbiAgICAgICAgMyxcbiAgICAgICAgMTkzLFxuICAgICAgICAxMyxcbiAgICAgICAgMTcxLFxuICAgICAgICA4NixcbiAgICAgICAgMTlcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE0NCxcbiAgICAgICAgNjYsXG4gICAgICAgIDYzLFxuICAgICAgICA2MCxcbiAgICAgICAgMzksXG4gICAgICAgIDIzNCxcbiAgICAgICAgMjUyLFxuICAgICAgICAyMTEsXG4gICAgICAgIDU1LFxuICAgICAgICAyMDgsXG4gICAgICAgIDU1LFxuICAgICAgICAxNTIsXG4gICAgICAgIDI1MixcbiAgICAgICAgMTUwLFxuICAgICAgICAxMjUsXG4gICAgICAgIDE1NCxcbiAgICAgICAgNTQsXG4gICAgICAgIDIxNixcbiAgICAgICAgMTcyLFxuICAgICAgICAyMDQsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMjM1LFxuICAgICAgICAyMzMsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMTgwLFxuICAgICAgICAxNDUsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMTU1LFxuICAgICAgICA3NCxcbiAgICAgICAgMTU2LFxuICAgICAgICA1NixcbiAgICAgICAgNjZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjMyLFxuICAgICAgICAxNjksXG4gICAgICAgIDkzLFxuICAgICAgICAxMjIsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTA3LFxuICAgICAgICAxNjEsXG4gICAgICAgIDMwLFxuICAgICAgICA1NCxcbiAgICAgICAgMTgzLFxuICAgICAgICAxMjcsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTkyLFxuICAgICAgICAyMjksXG4gICAgICAgIDIzOCxcbiAgICAgICAgMTQ0LFxuICAgICAgICAxNjAsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMjE4LFxuICAgICAgICAyMzQsXG4gICAgICAgIDEzNixcbiAgICAgICAgMjMwLFxuICAgICAgICAyNDQsXG4gICAgICAgIDM0LFxuICAgICAgICAyNDAsXG4gICAgICAgIDY0LFxuICAgICAgICA0OSxcbiAgICAgICAgOCxcbiAgICAgICAgMTA3LFxuICAgICAgICAzMSxcbiAgICAgICAgMTc5LFxuICAgICAgICA1MFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNTIsXG4gICAgICAgICAgNzgsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgMTUzLFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAxMjMsXG4gICAgICAgICAgMjYsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICAyOSxcbiAgICAgICAgICAyNDMsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgMTE3LFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDIxMixcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgNzYsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTY4LFxuICAgICAgICAgIDEyMFxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgMjMsXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDE0NCxcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDEwOCxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDcsXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgNjYsXG4gICAgICAgICAgODEsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMTQsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMjksXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgNTcsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgMjE0LFxuICAgICAgICAgIDkxXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNixcbiAgICAgICAgNDksXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjIxLFxuICAgICAgICAyMjksXG4gICAgICAgIDEzOSxcbiAgICAgICAgODcsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTY1LFxuICAgICAgICAyOCxcbiAgICAgICAgMjI1LFxuICAgICAgICAxMTYsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMjMyLFxuICAgICAgICAxNzAsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMixcbiAgICAgICAgMTM5LFxuICAgICAgICAxMjYsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMTAzLFxuICAgICAgICAxODMsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMjQ0LFxuICAgICAgICA3NyxcbiAgICAgICAgMTk5LFxuICAgICAgICAxMDksXG4gICAgICAgIDIyMSxcbiAgICAgICAgMjEzLFxuICAgICAgICAyMzMsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTQ5LFxuICAgICAgICA2NixcbiAgICAgICAgMjM3LFxuICAgICAgICAxNjAsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTg3LFxuICAgICAgICAxNTQsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTcyLFxuICAgICAgICAxMDUsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTQ3LFxuICAgICAgICAyOCxcbiAgICAgICAgNDYsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMjE5LFxuICAgICAgICAxMTUsXG4gICAgICAgIDYxLFxuICAgICAgICAxMTcsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMjI0LFxuICAgICAgICAyMzMsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMjM3LFxuICAgICAgICAyMzIsXG4gICAgICAgIDE1NSxcbiAgICAgICAgNDksXG4gICAgICAgIDQ4LFxuICAgICAgICAyMTQsXG4gICAgICAgIDg1LFxuICAgICAgICAyMjYsXG4gICAgICAgIDc3LFxuICAgICAgICA1XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiA2MyxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJoVU1jWEhrZVd1TTRBK3U3RGZoL2gvcE8xTkY3b1phSm01djhNd0FYSUlrPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzE5NDc3ODk5MEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNDM3NUM5MjBFNzVCNUZEOTQ0ODI0MjMyREZFRDRGMEZcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzE2NTQ0MDYzXG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMTk0Nzc4OTkwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIxRDAwMjQxRkQ2QkE4RkEyMjYyMDAzM0RERDIwNjhGN1wiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MTY1NDQwNjRcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiX2M3UnFsRnBSSlNJd2NST05xbVlSUVwiLFxuICBcInBob25lSWRcIjogXCIzZTE1MmFhOC0xZDY3LTQ0ZDQtOWNlYy1hODU5ZmQ1YmVkODBcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgODgsXG4gICAgICA1NCxcbiAgICAgIDQzLFxuICAgICAgMjE1LFxuICAgICAgMjQ0LFxuICAgICAgMzIsXG4gICAgICAyNDEsXG4gICAgICAyMDIsXG4gICAgICA5OCxcbiAgICAgIDEzNSxcbiAgICAgIDExNCxcbiAgICAgIDIyOSxcbiAgICAgIDIyNCxcbiAgICAgIDEzMyxcbiAgICAgIDQ5LFxuICAgICAgOTEsXG4gICAgICAxNDYsXG4gICAgICAyNDEsXG4gICAgICAyMixcbiAgICAgIDE1N1xuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RlcmVkXCI6IHRydWUsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxNCxcbiAgICAgIDgwLFxuICAgICAgMTYsXG4gICAgICAyMDYsXG4gICAgICAxOTgsXG4gICAgICAxNDAsXG4gICAgICA0MCxcbiAgICAgIDIwNyxcbiAgICAgIDE4LFxuICAgICAgMTc2LFxuICAgICAgMzcsXG4gICAgICAzMCxcbiAgICAgIDE4OCxcbiAgICAgIDU2LFxuICAgICAgMTksXG4gICAgICA0NCxcbiAgICAgIDIxMSxcbiAgICAgIDY0LFxuICAgICAgMTQ3LFxuICAgICAgMTQ4XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJwYWlyaW5nQ29kZVwiOiBcIkNRVjQ5QlJMXCIsXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCI5MjMxOTQ3Nzg5OTA6MTFAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJCYWxvY2hcIixcbiAgICBcImxpZFwiOiBcIjExMDU4Mjk3NTk3MTQwNzoxMUBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNQdVIxL0lGRUxqRXdiSUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIlFSUG5iVWQ5Z3d5VXV3L296cnNmOTJrbzExclFHSFlQdmUzbFMrakp5SGs9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiQlI3UXJBMGl2cmVpNTdoUFZlMUF3SDA1RHFxeVUxcGZrUGlWL0ZuWWJKZ3QvUW1xbXJtQ1BjM1A1enhBY243OEpwSTRYTmpHVHNUTmlCdDFqSkI4QWc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiS09sbCt1R29TYUV1UnJySHduVDZ6STVSV0hEVGdZbU5HbTJKRlEwakpZY3owaUY2SFl0YituWE5qZCtlcVZzR0dzQ0VQb0owYlJialNqdzRKMU44QWc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTIzMTk0Nzc4OTkwOjExQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgNjUsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDEwOSxcbiAgICAgICAgICA3MSxcbiAgICAgICAgICAxMjUsXG4gICAgICAgICAgMTMxLFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDE0OCxcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDIwNixcbiAgICAgICAgICAxODcsXG4gICAgICAgICAgMzEsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDEwNSxcbiAgICAgICAgICA0MCxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgMjA4LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAxNSxcbiAgICAgICAgICAxODksXG4gICAgICAgICAgMjM3LFxuICAgICAgICAgIDIyOSxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDIwMCxcbiAgICAgICAgICAxMjFcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcInNtYmFcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcxNjU0NDA2MCxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUl3VFwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSXdULmpzb24iOiAie1wia2V5RGF0YVwiOlwiTCswL1ZMSUowaVFkMXlCazhrUjhhL3ZxcTFoS1ZmVHpvdEhDUVlLZDFGUT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNTgyNjgwMzE1LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTY1NDQwNjQwNTRcIn0iCn0=" ;


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: SULTAN KHAN Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.9",
  caption : process.env.CAPTION || "سلطان➳🇲R" , // ```『 SULTAN KHAN BALOCH  』```", //*『SULTAN • KHAN BALOCH』*\n https://youtube.com/@Y.BGamer110"),
 
  author : process.env.PACK_AUTHER|| "SULTAN BALOCH",
  packname: process.env.PACK_NAME || "❤️",
  botname : process.env.BOT_NAME  || "SULTAN KHAN",
  ownername:process.env.OWNER_NAME|| "SULTAN KHAN",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "public",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SULTAN KHAN",



};

























global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
