const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""

global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"


global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/YosafN/YOUSAF-KHAN";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VaXTvQ7JuyAHXjJBs61T";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029VaXTvQ7JuyAHXjJBs61T" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/4c6df8243017a1f7e7890.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923115971525" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "MA NI BTAO GA";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923115971525,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://yousaf khan-vtsf.onrender.com/";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_12_11_05_24_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjE2LFxuICAgICAgICA0OSxcbiAgICAgICAgMjA4LFxuICAgICAgICAxMTcsXG4gICAgICAgIDIzNixcbiAgICAgICAgODEsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMTc2LFxuICAgICAgICAyMTYsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMTM0LFxuICAgICAgICA3LFxuICAgICAgICA5NyxcbiAgICAgICAgMTczLFxuICAgICAgICAyNDAsXG4gICAgICAgIDU1LFxuICAgICAgICAxMDIsXG4gICAgICAgIDI5LFxuICAgICAgICA4OCxcbiAgICAgICAgMzgsXG4gICAgICAgIDUyLFxuICAgICAgICAxMTksXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTgxLFxuICAgICAgICAzMCxcbiAgICAgICAgMTQ2LFxuICAgICAgICAyNTMsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTYzLFxuICAgICAgICAyMDgsXG4gICAgICAgIDEwOCxcbiAgICAgICAgODFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMjUwLFxuICAgICAgICAxMzYsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTY0LFxuICAgICAgICAxNCxcbiAgICAgICAgMjQ5LFxuICAgICAgICAyOSxcbiAgICAgICAgMjEsXG4gICAgICAgIDE0NyxcbiAgICAgICAgOTQsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTY1LFxuICAgICAgICAzMixcbiAgICAgICAgNjAsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTgyLFxuICAgICAgICAyMyxcbiAgICAgICAgMjI0LFxuICAgICAgICAzMSxcbiAgICAgICAgNjMsXG4gICAgICAgIDM1LFxuICAgICAgICAzMyxcbiAgICAgICAgNDAsXG4gICAgICAgIDYwLFxuICAgICAgICA4LFxuICAgICAgICAxNjYsXG4gICAgICAgIDI1MixcbiAgICAgICAgNSxcbiAgICAgICAgMjI1LFxuICAgICAgICAzMFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTA0LFxuICAgICAgICAxNDMsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMjI2LFxuICAgICAgICA5NyxcbiAgICAgICAgMjM4LFxuICAgICAgICAxNTUsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTk4LFxuICAgICAgICAyOSxcbiAgICAgICAgMTk3LFxuICAgICAgICAxNzksXG4gICAgICAgIDI2LFxuICAgICAgICAxMTMsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTY4LFxuICAgICAgICAxNTEsXG4gICAgICAgIDIwNixcbiAgICAgICAgMTQ1LFxuICAgICAgICA3MyxcbiAgICAgICAgMTMyLFxuICAgICAgICA0OSxcbiAgICAgICAgNTIsXG4gICAgICAgIDEyNyxcbiAgICAgICAgODksXG4gICAgICAgIDExNixcbiAgICAgICAgMTAzLFxuICAgICAgICA3MSxcbiAgICAgICAgMTUyLFxuICAgICAgICAxMixcbiAgICAgICAgNjcsXG4gICAgICAgIDkzXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE1OSxcbiAgICAgICAgNCxcbiAgICAgICAgODIsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTMsXG4gICAgICAgIDIwNSxcbiAgICAgICAgMTE1LFxuICAgICAgICAxNjMsXG4gICAgICAgIDc3LFxuICAgICAgICAxNDQsXG4gICAgICAgIDE0LFxuICAgICAgICA3MCxcbiAgICAgICAgODEsXG4gICAgICAgIDE2MSxcbiAgICAgICAgODAsXG4gICAgICAgIDE4MCxcbiAgICAgICAgNzgsXG4gICAgICAgIDE0MixcbiAgICAgICAgMTM0LFxuICAgICAgICAxMzAsXG4gICAgICAgIDUzLFxuICAgICAgICA2MixcbiAgICAgICAgMTgwLFxuICAgICAgICAyMzksXG4gICAgICAgIDU3LFxuICAgICAgICAyNSxcbiAgICAgICAgMTUzLFxuICAgICAgICAxMzIsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTUwLFxuICAgICAgICA3OSxcbiAgICAgICAgOTJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEzNixcbiAgICAgICAgMjAzLFxuICAgICAgICA0MixcbiAgICAgICAgOTAsXG4gICAgICAgIDE2LFxuICAgICAgICAxNTMsXG4gICAgICAgIDQ2LFxuICAgICAgICA1NCxcbiAgICAgICAgMTY3LFxuICAgICAgICAyNDQsXG4gICAgICAgIDU4LFxuICAgICAgICAyMzcsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTk5LFxuICAgICAgICAxODQsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMTA2LFxuICAgICAgICAxMDUsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTE3LFxuICAgICAgICA0NSxcbiAgICAgICAgMTY4LFxuICAgICAgICA2MCxcbiAgICAgICAgNzcsXG4gICAgICAgIDIsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMjExLFxuICAgICAgICA0OCxcbiAgICAgICAgMjQ0LFxuICAgICAgICA4NixcbiAgICAgICAgMTg1LFxuICAgICAgICA4MVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMDYsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTMzLFxuICAgICAgICAxNDgsXG4gICAgICAgIDE1OSxcbiAgICAgICAgNzUsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTY0LFxuICAgICAgICAxMjAsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTExLFxuICAgICAgICAyNTMsXG4gICAgICAgIDg2LFxuICAgICAgICAyMyxcbiAgICAgICAgMjM5LFxuICAgICAgICA1MSxcbiAgICAgICAgMjA1LFxuICAgICAgICAyNDAsXG4gICAgICAgIDE4MyxcbiAgICAgICAgNixcbiAgICAgICAgMTMxLFxuICAgICAgICA1NixcbiAgICAgICAgOTcsXG4gICAgICAgIDIzOSxcbiAgICAgICAgNjQsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMjQ1LFxuICAgICAgICAxMDIsXG4gICAgICAgIDM1LFxuICAgICAgICAyMzksXG4gICAgICAgIDE1MixcbiAgICAgICAgMTIwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDQwLFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDQsXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDEzNyxcbiAgICAgICAgICAyMzgsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDIwNyxcbiAgICAgICAgICA5NixcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgMTY0LFxuICAgICAgICAgIDI0OSxcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgMjA0LFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICAxOCxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMTg1LFxuICAgICAgICAgIDEzNyxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgMTgsXG4gICAgICAgICAgMTE3LFxuICAgICAgICAgIDEwNyxcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDI1MSxcbiAgICAgICAgICA4NixcbiAgICAgICAgICA5N1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMjE5LFxuICAgICAgICAgIDYwLFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMixcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICAxMjAsXG4gICAgICAgICAgMzYsXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMTcxLFxuICAgICAgICAgIDEwOCxcbiAgICAgICAgICA3NCxcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDIwNyxcbiAgICAgICAgICAxMzQsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICAzOSxcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMjksXG4gICAgICAgICAgMjdcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA3OCxcbiAgICAgICAgNjIsXG4gICAgICAgIDg5LFxuICAgICAgICAyMDEsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMjQzLFxuICAgICAgICAxMDUsXG4gICAgICAgIDU1LFxuICAgICAgICAxNDYsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMzcsXG4gICAgICAgIDYsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTcwLFxuICAgICAgICA0MCxcbiAgICAgICAgMTUyLFxuICAgICAgICAxNyxcbiAgICAgICAgODAsXG4gICAgICAgIDE5NSxcbiAgICAgICAgODMsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMjU0LFxuICAgICAgICA4NyxcbiAgICAgICAgNzQsXG4gICAgICAgIDEzMixcbiAgICAgICAgMjEzLFxuICAgICAgICA2MyxcbiAgICAgICAgMzAsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjA5LFxuICAgICAgICAxOTMsXG4gICAgICAgIDE0NixcbiAgICAgICAgMzYsXG4gICAgICAgIDE2NyxcbiAgICAgICAgNDAsXG4gICAgICAgIDEyNSxcbiAgICAgICAgNTIsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMjMyLFxuICAgICAgICA0NixcbiAgICAgICAgNzUsXG4gICAgICAgIDYsXG4gICAgICAgIDE1NSxcbiAgICAgICAgODMsXG4gICAgICAgIDEyNCxcbiAgICAgICAgNDgsXG4gICAgICAgIDExMyxcbiAgICAgICAgMjQ1LFxuICAgICAgICA4MCxcbiAgICAgICAgMzIsXG4gICAgICAgIDIzMixcbiAgICAgICAgNjEsXG4gICAgICAgIDI1LFxuICAgICAgICAzMixcbiAgICAgICAgMTcsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMTI4LFxuICAgICAgICAyMzgsXG4gICAgICAgIDE0NyxcbiAgICAgICAgNjgsXG4gICAgICAgIDczLFxuICAgICAgICA4NSxcbiAgICAgICAgMTE3LFxuICAgICAgICAxMzBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDMyLFxuICBcImFkdlNlY3JldEtleVwiOiBcIjhoRmF0SUFlTDV4c0lKaVptR1dZcnJTaS84LzVIYkE5WEsxRkd1NG9GM1E9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMTk0Nzc4OTkwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCIzQTNGNkVGQjA2RUJGMDY4OEVDMzg3OUMxM0UzNzQ5QVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MTY1NTI3MDFcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjMxOTQ3Nzg5OTBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkNFMDVEN0MzOTAwMUMxODA4NjY4NkI3Qjc2QkQxQjFEXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNjU1MjcwMVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzE5NDc3ODk5MEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiRTYzMkVGQzQyQjhBNDc0QzBCODVFNzZBMUExODcwMzFcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzE2NTUyNzA2XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIlhuOG5qZktnUzBTT2Z5b3puN0JIdUFcIixcbiAgXCJwaG9uZUlkXCI6IFwiNDM4ZTBlZmEtMDZhYS00MzczLWJlMjEtZmE1ZGJiZTgxMzdlXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDg3LFxuICAgICAgMTMyLFxuICAgICAgMTAsXG4gICAgICAyMzcsXG4gICAgICA0MyxcbiAgICAgIDE3NixcbiAgICAgIDEyMixcbiAgICAgIDc3LFxuICAgICAgMTM3LFxuICAgICAgODEsXG4gICAgICA5NixcbiAgICAgIDE4NixcbiAgICAgIDQ0LFxuICAgICAgMTU2LFxuICAgICAgMTYzLFxuICAgICAgMjUzLFxuICAgICAgNTksXG4gICAgICAxNDcsXG4gICAgICA0OSxcbiAgICAgIDM5XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDkxLFxuICAgICAgMTcsXG4gICAgICAzMCxcbiAgICAgIDMxLFxuICAgICAgMTc1LFxuICAgICAgNjYsXG4gICAgICAxNjYsXG4gICAgICAxMDMsXG4gICAgICAxODQsXG4gICAgICAxNTQsXG4gICAgICAzMCxcbiAgICAgIDEwNyxcbiAgICAgIDE1NSxcbiAgICAgIDQwLFxuICAgICAgMjgsXG4gICAgICAyNDYsXG4gICAgICAyNDAsXG4gICAgICAzMSxcbiAgICAgIDIwOSxcbiAgICAgIDEyOVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCJWR0pRS05RNVwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTIzMTk0Nzc4OTkwOjEzQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJuYW1lXCI6IFwiQmFsb2NoXCIsXG4gICAgXCJsaWRcIjogXCIxMTA1ODI5NzU5NzE0MDc6MTNAbGlkXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDUDJSMS9JRkVQYUh3cklHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJRUlBuYlVkOWd3eVV1dy9venJzZjkya28xMXJRR0hZUHZlM2xTK2pKeUhrPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcInc3ZEhyZVNiYUp5dDM1NnlFdWJqakZ4cVRjQjVTZ3U5OWVvL25ySnJ0ZUNCcmt0eDU4c1l4Y3JKViszcGtPM0MyUmNib3h4Q2RrWGVhSmJnbWRmQURRPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIlBUai9RZUg3L2NpNVRKc1FISzRnaTBwRyt2NTRyVk5UNnZXNFlHdjZZbU15YmNVVE04d3pnajlXakZNaGkzUk9HN3dpTjFTbXVzZWRtaXVTQTNNWWlBPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjkyMzE5NDc3ODk5MDoxM0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDIzMSxcbiAgICAgICAgICAxMDksXG4gICAgICAgICAgNzEsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICAxMixcbiAgICAgICAgICAxNDgsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICAyMDYsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDMxLFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAxMDUsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDkwLFxuICAgICAgICAgIDIwOCxcbiAgICAgICAgICAyNCxcbiAgICAgICAgICAxMTgsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgMjMyLFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMTIxXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MTY1NTI2OTgsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFJd1hcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUl3WC5qc29uIjogIntcImtleURhdGFcIjpcIndUZ2tIM1ZROVBuWWJ0ZmxpbC9WZDdJUEo4cnUrM2hJR0lvNHVtL0VQUEk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTU4MjY4MDMxNyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzE2NTUyNzAxNDI3XCJ9Igp9" ;


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: YOUSAF KHAN Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.9",
  caption : process.env.CAPTION || "سلطان➳🇲R" , // ```『 SULTAN KHAN BALOCH  』```", //*『YOUSAF • KHAN BALOCH』*\n https://youtube.com/@Y.BGamer110"),
 
  author : process.env.PACK_AUTHER|| "SULTAN BALOCH",
  packname: process.env.PACK_NAME || "❤️",
  botname : process.env.BOT_NAME  || "SULTAN KHAN",
  ownername:process.env.OWNER_NAME|| "SULTAN KHAN",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "public",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "YOUSAF KHAN",



};

























global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
